name: Variable Workflow - 1
# on:
#   push:
#     branches:
#       - main
#       - feature
#   workflow_dispatch:
env:
  GAME: CALL OF DUTY
jobs:
  COPY_THE_BINARY:
    env:
      GAME_VERSION: "MODERN WARFARE 2"
    runs-on: ubuntu-latest
    steps:
      - name: DOWNLOAD TPHE BINARY
        run: echo "$GAME:$GAME_VERSION download has been $STATUS"
        env:
          STATUS: "STARTED"