name: Testing Configuration Variable
on:
  workflow_dispatch:
jobs:
  COPY_THE_BINARY:
    env:
      GAME_VERSION: "run"
    runs-on: ubuntu-latest
    steps:
      - name: DOWNLOAD THE BINARY
        run: echo "${{vars.GAME}}:$GAME_VERSION download has been $STATUS"
        env:
          STATUS: "STARTED"
