name: Testing Context Variable
on:
  workflow_dispatch:
env:
  GAME_VERSION: "run"
jobs:
  COPY_THE_BINARY:
    runs-on: ubuntu-latest
    steps:
      - name: DOWNLOAD THE BINARY
        run: echo "${{vars.GAME}}:$GAME_VERSION download has been $STATUS"
        env:
          STATUS: "STARTED"
  CONTEXT_VARIABLE:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Context Variable
        run: |
          echo "Name of the workflow is ${{ github.workflow }}"
          echo "Name of the repository is ${{ github.repository }}"
          echo "Name of the owner is ${{ github.repository_owner }}"
          echo "Name of the branch is ${{ github.ref }}"
          echo "Name of the commit is ${{ github.sha }}"
          echo "${{vars.GAME}}:$GAME_VERSION download has been $STATUS"
        env:
          STATUS: "COMPLETED"
