name: Testing Secrets
on:
  workflow_dispatch:
jobs:
  Enter the password:
    runs-on: ubuntu-latest
    steps:
      - name: Enter the password
        run: |
          echo "The password is ${{ secrets.PASSWORD }}"
          echo $PASSWORD
        env:
          PASSWORD: ${{ secrets.PASSWORD }}